### PR TITLE
Reload Tape

### PR DESCRIPTION
**Pull request by yosimasu**
1. Add options.reload
2. If options.reload = true, reload the tape

@mbaertschi 
I can not write a test case for this, because of Jest [issue](https://github.com/facebook/jest/issues/6066#issuecomment-384272244).

### CODE REVIEW

**Comment by mbaertschi** [comment]
Hi @yosimasu 

I would be great to have two options:

1. `options.refresh = true` refreshes the tape content (but does not delete it beforehand)
2. `options.reload = true` deletes the tape and reloads it

what do you think about this?

**Comment by mbaertschi** [comment]
Hi @yosimasu 

This looks good. Thank you four your contribution, I really appreciate it!

I will add `option.reload` in a later stage myself. This would be helpful in the test-writing-stage where one might has to delete and re-add the recorded test-files multiple times. This happens to me from time to time :-)

**Comment by yosimasu** [comment]
@mbaertschi 

I think the reload option is a great idea.
I want to add an enhancement: 
1. add reloadStatues option, if reloadStatuses is undefined or empty, reload always.
2. if match, reload it,
3. if no match, use existed tape instead

**Comment by mbaertschi** [comment]
Hi @yosimasu 

Feel free to add this extension. Please be aware of the existing `option.relaod` configuration which simply deletes the file in the [index.js](https://github.com/mbaertschi/node-vcr/blob/040f0f6d64a9ee8215acf7485f7573a06e9905c7/src/index.js#L52) source.

**Pull request merged**
